name: oneclick_stems
description: A Flutter app for one-click MP3 stem separation
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  file_picker: ^6.0.0

flutter:
  uses-material-design: true
